title: yuki's blog
description: 作ったプログラムの解説をするブログです。
twitter_username: yuki_eeee
github_username: yuki67
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .vscode
  - non-markdowns

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
